apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecopsbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecopsbuggy
  template:
    metadata:
      labels:
        app: devsecopsbuggy
    spec:
      containers:
      - name: devsecopsbuggy
        image: 413042731683.dkr.ecr.ap-south-1.amazonaws.com/devsecops
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecopsbuggy
    k8s-app: devsecopsbuggy
  name: devsecopsbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: devsecopsbuggy
